# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b63d1a30-5348-4304-9950-2bb267223e3b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-68a6a26b-400b-4b9a-aeb2-9da649ebaa6a".device = "/dev/disk/by-uuid/68a6a26b-400b-4b9a-aeb2-9da649ebaa6a";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2e4ef339-0e3b-4554-b187-854ae380e052"; }
    ];

  boot.resumeDevice = "/dev/disk/by-label/swap"; # 2023-12-02: required https://nixos.org/manual/nixos/stable/release-notes#sec-release-23.11 -> "boot.resumeDevice must be specified when hibernating if not in EFI mode."

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
